package com.jkys.zyyh.mic.dao.entity;

import lombok.Data;

import java.util.Date;

/**
 *
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mic_msg
 */
@Data
public class MicMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.id
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   消息标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.msg_identify
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private String msgIdentify;

    /**
     * Database Column Remarks:
     *   院内是否已消费  1 表示是，0 表示否

     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.is_consume
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Integer consume;

    /**
     * Database Column Remarks:
     *   院内消费重试次数 默认 0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.retry_count
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Integer retryCount;

    /**
     * Database Column Remarks:
     *   最大重试次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.max_retry_count
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Integer maxRetryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.gmt_create
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.gmt_modify
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private Date gmtModify;

    /**
     * 消息文本
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mic_msg.content
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    private String content;

    //消息业务类型
    private String micBizType;
    //消息的业务事件
    private String micBizEvent;

}