package com.jkys.zyyh.mic.dao.mapper;

import com.jkys.zyyh.mic.dao.entity.MicMsg;
import com.jkys.zyyh.mic.dao.entity.MicMsgHistory;
import com.jkys.zyyh.mic.dao.query.MicMsgQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MicMsgHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mic_msg
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    int insertBatch(@Param("record") List<MicMsgHistory> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mic_msg
     *
     * @mbg.generated Thu Jan 02 15:19:49 CST 2020
     */
    int insertSelective(MicMsgHistory record);

    /**
     * id 升序
     * @param query
     * @return
     */
    MicMsgHistory selectOne(MicMsgQuery query);
}